version: '3.8'

services:
    app:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: sample_project
        ports:
            - 8000:8000
        env_file:
            - .env
        entrypoint: bash -c './entrypoint.sh'
        volumes:
            - .:/app
        depends_on:
            postgres_db:
                condition: service_healthy
        restart: on-failure

    postgres_db:
        image: postgres:15.1
        container_name: postgres_db
        restart: on-failure
        env_file:
            - .env
        volumes:
            - books_db_data:/var/lib/postgresql/data
        ports:
            - 5432:5423
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}',
                ]
            interval: 5s
            timeout: 3s
            retries: 3

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:6
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - postgres_db
        volumes:
            - sample_project_pgadmin_data:/var/lib/pgadmin
        ports:
            - 8080:80
volumes:
    books_db_data:
        driver: local
    sample_project_pgadmin_data:
        driver: local
